## A TENSOR is an array that is, a data structure that stores a collection of numbers that are accessible individually using an index, and that can be indexed with multiple indices.

In [5]:
import torch

a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

Whenever you see

torch.tensor(...)

don't think

"It's like a Python list."

Think

"It's a view over a block of raw memory plus some metadata."


each elements in a python list
are stored as an object of their respective datatype and so they aren't continuous.

In [7]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

In [8]:
points = torch.tensor([4, 1, 5, 3, 2, 1])

In [9]:
points

tensor([4, 1, 5, 3, 2, 1])

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0,3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [11]:
points.shape

torch.Size([3, 2])

In [12]:
points[0,1]

tensor(1.)

In [13]:
some_list = list(range(6))
some_list[:]
some_list[1:4]
some_list[1:]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

[1, 3]

## Broadcasting

✓ Same size

OR

✓ One of them is 1
___
(3,1)

×

(1,3)

___

1         
2      x  10 20 30                 
3      

___

10 20 30

20 40 60

30 60 90

In [14]:
## NAMED TENSORS
img_t = torch.randn(3,5,5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights.shape , img_t.shape


(torch.Size([3]), torch.Size([3, 5, 5]))

In [15]:
batch_t = torch.randn(2,3,5,5) # shape [ batch, channels, rows, columns]

In [16]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [17]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [18]:
img_weights  = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [19]:
x = torch.tensor([[[[1],[2]],[[1],[2]]],[[[1],[2]],[[1],[2]]]])
x.shape

torch.Size([2, 2, 2, 1])

In [20]:
double_points = torch.ones( 10 , 2 , dtype=torch.double)
short_points = torch.tensor([[1,3],[3,4]], dtype=torch.short)

In [21]:
short_points.dtype , double_points.dtype

(torch.int16, torch.float64)

In [22]:
# Casting method to create tensors

double_points = torch.zeros(10,2).double()
short_points = torch.ones(10,2).short()

In [23]:
a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)
a.shape , a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [24]:
# other way of transposing.

a_t = a.transpose(0,1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [25]:
import torch

# Empty tensor (uninitialized values)
x = torch.empty(2,3)

# All zeros
x = torch.zeros(2,3)

# All ones
x = torch.ones(2,3)

# Random numbers
x = torch.rand(2,3)

# Standard normal distribution
x = torch.randn(2,3)

# Tensor from Python list
x = torch.tensor([[1,2],[3,4]])

# Sequence
x = torch.arange(10)

# Evenly spaced values
x = torch.linspace(0,1,5)

In [26]:
x = torch.randn(3,4,5)

x.shape
x.ndim
x.numel()
x.dtype
x.device

device(type='cpu')

In [27]:
x = torch.arange(12).reshape(3,4)

print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [28]:
x = torch.arange(12)

x.reshape(3,4)

print(x.view(3,4))

x.flatten()
print(x)
x.unsqueeze(0)
print(x)
x.squeeze()

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
x = torch.randn(32,3,224,224)
print(x)
x.permute(0,2,3,1)

tensor([[[[-1.3719,  0.1153,  0.4169,  ..., -0.1530, -1.0514, -1.1146],
          [ 0.9150,  1.7835,  1.0194,  ...,  0.9469, -1.1495, -0.4778],
          [-1.5366, -0.9243,  0.8682,  ...,  0.2245,  0.4250, -0.3539],
          ...,
          [-0.0614,  2.6991,  1.4651,  ...,  0.9349, -0.0146,  1.0793],
          [ 1.7831, -0.8258,  0.4434,  ...,  0.2085,  1.4998, -0.3389],
          [ 1.8148,  0.2367, -0.4142,  ..., -0.5847,  0.2305, -0.1811]],

         [[-0.3816,  0.1673, -1.2037,  ..., -0.1024, -0.5764,  0.1326],
          [-1.3550,  0.9002, -1.3725,  ...,  0.1171,  0.5392,  1.4653],
          [ 0.6166,  1.9702, -0.6477,  ..., -0.9442, -1.5440,  1.0951],
          ...,
          [-0.5072,  2.0527, -0.1504,  ...,  1.2535,  0.2980, -2.1243],
          [-1.5120, -0.3130,  0.7429,  ..., -0.7408,  0.0365,  0.0627],
          [-0.1949, -1.3466,  0.7096,  ...,  2.4414,  0.0806,  0.9839]],

         [[-0.4074,  1.1776,  0.0869,  ..., -0.5222,  0.7389, -0.1568],
          [-1.4346,  1.1775, -

tensor([[[[-1.3719, -0.3816, -0.4074],
          [ 0.1153,  0.1673,  1.1776],
          [ 0.4169, -1.2037,  0.0869],
          ...,
          [-0.1530, -0.1024, -0.5222],
          [-1.0514, -0.5764,  0.7389],
          [-1.1146,  0.1326, -0.1568]],

         [[ 0.9150, -1.3550, -1.4346],
          [ 1.7835,  0.9002,  1.1775],
          [ 1.0194, -1.3725, -0.3716],
          ...,
          [ 0.9469,  0.1171, -0.4489],
          [-1.1495,  0.5392, -1.1971],
          [-0.4778,  1.4653,  1.0050]],

         [[-1.5366,  0.6166,  0.4988],
          [-0.9243,  1.9702, -0.4171],
          [ 0.8682, -0.6477, -0.1014],
          ...,
          [ 0.2245, -0.9442, -1.1784],
          [ 0.4250, -1.5440, -0.0657],
          [-0.3539,  1.0951,  2.2024]],

         ...,

         [[-0.0614, -0.5072,  1.1008],
          [ 2.6991,  2.0527,  0.2733],
          [ 1.4651, -0.1504,  0.9573],
          ...,
          [ 0.9349,  1.2535,  1.6323],
          [-0.0146,  0.2980, -0.0450],
          [ 1.0793, -2

In [30]:
x = torch.arange(12).reshape(3,4)

print(x)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [31]:
torch.abs(x)

torch.sin(x)

torch.cos(x)

torch.exp(x)

torch.log(x)

torch.sqrt(x)

tensor([[0.0000, 1.0000, 1.4142, 1.7321],
        [2.0000, 2.2361, 2.4495, 2.6458],
        [2.8284, 3.0000, 3.1623, 3.3166]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

second_point = points[1]
second_point.storage_offset()

2

# Practice Tensors

## notes:

1. Pytorch stores numbers in one continuous block. The storage doesn't know rows or columns exists
2. Which storage element is tensor[i,j] = storage_offset + stride[0]*i + stride[1]*j

In [33]:
a = torch.arange(24)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [34]:
a = torch.arange(24).reshape(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [35]:
a.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [36]:
a.contiguous()

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [37]:
a = torch.arange(12)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
b = a.view(3,4)
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [39]:
a = torch.arange(24).view(2,3,4)
a

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [40]:
df = pd.read_csv('./datasets/winequality-white.csv', sep=';')

NameError: name 'pd' is not defined

In [ ]:
df

In [ ]:
df.isnull().sum()

In [ ]:
wineq = torch.tensor(df.values)

In [ ]:
wineq.shape, wineq.dtype

In [ ]:
wineq = wineq.to(dtype=torch.float32)

In [ ]:
wineq.dtype

In [ ]:
data = wineq[:, : -1]
data, data.shape

In [ ]:
target = wineq[:, -1]
target, target.shape

In [ ]:
target = wineq[:, -1].long()
target

In [ ]:
target_ohe = torch.zeros(target.shape[0], 10)
target_ohe.scatter_(1, target.unsqueeze(1), 1.0) 

In [ ]:
random_indices = torch.randint(0 , len(target), (5,))
print(target[random_indices])
print(target_ohe[random_indices])

In [ ]:
target_unsqueezed = target.unsqueeze(1)
target_unsqueezed

In [ ]:
data_mean = torch.mean(data, dim= 0)
data_mean

In [ ]:
data_var = torch.var(data, dim=0)
data_var

In [ ]:
data_normalized = (data - data_mean) / torch.sqrt(data_var)
data_normalized

## Manually Setting Threshold

In [ ]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

In [ ]:
bad_data = data[bad_indexes]
bad_data.shape

In [ ]:
bad_data = data[target <=3]
mid_data = data[target > 3]
good_data = data[target >= 7]

bad_mean = torch.mean(bad_data, dim=0)
mid_mean = torch.mean(mid_data, dim=0)
good_mean = torch.mean(good_data, dim=0)


# Work on time series. 

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
days = pd.read_csv('datasets/day.csv')

hours.columns
days.columns

hours = torch.tensor(hours)
days = torch.tensor(days)


## Tensors don't accept strings

In [ ]:
dates = pd.to_datetime(hours['dteday'])

features = hours.drop(columns=['dteday'])

hours_tensor = torch.tensor(
    features.to_numpy(),
    dtype = torch.float32
)

In [ ]:
features

In [ ]:
hours_tensor.stride()

In [ ]:
daily_bikes = hours_tensor.view(-1, 24, 17)

In [ ]:
print(hours.shape)
print(hours_tensor.shape)

In [ ]:
daily_bikes = hours_tensor.view(-1, 24, 16)

In [ ]:
# new updated uci dataset is in different format.

## Low-level NLP tasks include:

    Sentence boundary detection: abbreviations and titles (‘m.g.,’ ‘Dr.’) complicate this task, as do items in a list or templated utterances (eg, ‘MI [x], SOB[]’).

    Tokenization: identifying individual tokens (word, punctuation) within a sentence. A lexer plays a core role for this task and the previous one. In biomedical text, tokens often contain characters typically used as token boundaries, for example, hyphens, forward slashes (‘10 mg/day,’ ‘N-acetylcysteine’).

    Part-of-speech assignment to individual words (‘POS tagging’): in English, homographs (‘set’) and gerunds (verbs ending in ‘ing’ that are used as nouns) complicate this task.

    Morphological decomposition of compound words: many medical terms, for example, ‘nasogastric,’ need decomposition to comprehend them. A useful sub-task is lemmatization—conversion of a word to a root by removing suffixes. Non-English clinical NLP emphasizes decomposition; in highly synthetic languages (eg, German, Hungarian), newly coined compound words may replace entire phrases.22 Spell-checking applications and preparation of text for indexing/searching (in IR) also employ morphological analysis.

    Shallow parsing (chunking): identifying phrases from constituent part-of-speech tagged tokens. For example, a noun phrase may comprise an adjective sequence followed by a noun.

    Problem-specific segmentation: segmenting text into meaningful groups, such as sections, including Chief Complaint, Past Medical History, HEENT, etc.23


In [ ]:
with open ('datasets/shit_1.txt', encoding= 'utf8') as f:
    text = f.read()

In [ ]:
lines = text.split('\n')
line = lines[299]
line

In [ ]:
letter_t = torch.zeros(len(line), 128)
letter_t.shape

In [41]:
# ohe whole words

def clean_words(input_str):
    punctuation = '.,;:"!?”“_-'
    word_list = input_str.lower().replace('\n',' ').split()
    word_list = [word.strip(punctuation) for word in word_list]
    return word_list

words_in_line = clean_words(line)
line, words_in_line

('to find persons, especially female persons, not necessarily of noble',
 ['to',
  'find',
  'persons',
  'especially',
  'female',
  'persons',
  'not',
  'necessarily',
  'of',
  'noble'])

In [42]:
# mapping of unique words to indexes in encoding. 

word_list = sorted(set(clean_words(text)))
word2index_dict = {word: i for (i, word) in enumerate(word_list)}

len(word2index_dict), word2index_dict['find']

(7465, 2691)

In [43]:
word_t = torch.zeros(len(words_in_line), len(word2index_dict))

for i , word in enumerate(words_in_line):
    word_index = word2index_dict[word]
    word_t[i][word_index] = 1
    print('{:2} {:4} {}'.format(i, word_index, word))

print(word_t.shape)

 0 6680 to
 1 2691 find
 2 4914 persons
 3 2388 especially
 4 2657 female
 5 4914 persons
 6 4529 not
 7 4442 necessarily
 8 4618 of
 9 4507 noble
torch.Size([10, 7465])
