# Gradient descent learning with multiple inputs

> #### delta:
> A measure of how much higher or lower you want a node's value to be, to predict perfectly given the current training example

> #### weight_delta:
> A deivative-based estimate of the direction and amount you should move a weight to reduce node_delta, accounting for scaling, negative reversal, and stopping.

In [9]:
import numpy as np

# 1. Setup Data
weights = np.array([0.1, 0.2, -0.1])
alpha = 0.01

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# Our "Labels" (Goal Predictions)
win_or_lose_binary = np.array([1, 1, 0, 1])

def neural_network(input, weights):
    return input.dot(weights)

# 2. The Training Loop (Epochs)
for iteration in range(4000): # How many times to see the whole dataset
    error_for_all_lights = 0
    
    # Inner loop: Iterate through each game/example
    for i in range(len(win_or_lose_binary)):
        # Grab one example
        input_data = np.array([toes[i], wlrec[i], nfans[i]])
        true = win_or_lose_binary[i]
        
        # Forward Pass
        pred = neural_network(input_data, weights)
        
        # Calculate Error
        delta = pred - true
        error = delta**2
        error_for_all_lights += error # Tracking total error for this epoch
        
        # Calculate Weight Delta (The Gradient)
        weight_deltas = delta * input_data
        
        # Update Weights
        weights = weights - (alpha * weight_deltas)
        # -----------------------------------
        
    print(f"Iteration: {iteration+1} | Total Error: {error_for_all_lights:.5f}")

print(f"\nFinal Optimized Weights: {weights}")

Iteration: 1 | Total Error: 2.32730
Iteration: 2 | Total Error: 2.35269
Iteration: 3 | Total Error: 2.32943
Iteration: 4 | Total Error: 2.30643
Iteration: 5 | Total Error: 2.28368
Iteration: 6 | Total Error: 2.26118
Iteration: 7 | Total Error: 2.23893
Iteration: 8 | Total Error: 2.21692
Iteration: 9 | Total Error: 2.19516
Iteration: 10 | Total Error: 2.17364
Iteration: 11 | Total Error: 2.15235
Iteration: 12 | Total Error: 2.13130
Iteration: 13 | Total Error: 2.11048
Iteration: 14 | Total Error: 2.08990
Iteration: 15 | Total Error: 2.06953
Iteration: 16 | Total Error: 2.04939
Iteration: 17 | Total Error: 2.02948
Iteration: 18 | Total Error: 2.00978
Iteration: 19 | Total Error: 1.99029
Iteration: 20 | Total Error: 1.97103
Iteration: 21 | Total Error: 1.95197
Iteration: 22 | Total Error: 1.93312
Iteration: 23 | Total Error: 1.91448
Iteration: 24 | Total Error: 1.89604
Iteration: 25 | Total Error: 1.87781
Iteration: 26 | Total Error: 1.85977
Iteration: 27 | Total Error: 1.84193
Iteration:

## Freezing one weight
often used in transfer learning to stop certain weights from updating so they keep the *knowledge* they already have while other part of the network adapt.

In [12]:
import numpy as np

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
win_or_lose_binary = [1, 1, 0, 1]

true = win_or_lose_binary[0]
alpha = 0.01
weights = [0.1, 0.2, -.1]

input = np.array([toes[0],wlrec[0],nfans[0]])

def neural_network(input, weights):
    return input.dot(weights)

mask = np.array([1,1,0])

for i in range(10):
    
    pred = neural_network(input, weights)
    error = (pred - true) ** 2
    delta = pred - true
    weight_delta = (delta * input) * mask
    weights -= (weight_delta * alpha) 

    print(f"Iteration {i} | Error: {error:.6f} | Prediction: {pred:.4f}")

print(f"\nFinal Frozen Weights: {weights}")
    

Iteration 0 | Error: 0.019600 | Prediction: 0.8600
Iteration 1 | Error: 0.001464 | Prediction: 0.9617
Iteration 2 | Error: 0.000109 | Prediction: 0.9895
Iteration 3 | Error: 0.000008 | Prediction: 0.9971
Iteration 4 | Error: 0.000001 | Prediction: 0.9992
Iteration 5 | Error: 0.000000 | Prediction: 0.9998
Iteration 6 | Error: 0.000000 | Prediction: 0.9999
Iteration 7 | Error: 0.000000 | Prediction: 1.0000
Iteration 8 | Error: 0.000000 | Prediction: 1.0000
Iteration 9 | Error: 0.000000 | Prediction: 1.0000

Final Frozen Weights: [ 0.11637479  0.20125219 -0.1       ]


In [15]:
import numpy as np

# 3 input -> 3 outputs (9 weights)
            # toes %win # fans
weights = np.array([ [0.1, 0.1, -0.3],# hurt?
            [0.1, 0.2, 0.0], # win?
            [0.0, 1.3, 0.1] ])# sad?
alpha = 0.01

# Input data: [toes, win_percent, fans]
input_data = np.array([8.5,0.65,1.2])

# truth labels: [hurt_target, win_target, sad_target]
true = np.array([0.1,1.0,0.1])

def neural_network(input, weights):
    return input.dot(weights.T)

for i in range(10):
    pred = neural_network(input_data, weights)

    error = (pred-true) ** 2
    delta = pred - true
    #this creates a 3x3 matrix of "blame" for every connection
    weight_deltas = np.outer(delta, input_data)

    weights -= (alpha * weight_deltas)
    print(f"Iteration {i} | Total Error: {np.sum(error):.5f}")

print(f"\nFinal Optimized Weight Matrix:\n{weights}")
    


Iteration 0 | Total Error: 0.95565
Iteration 1 | Total Error: 0.06404
Iteration 2 | Total Error: 0.00429
Iteration 3 | Total Error: 0.00029
Iteration 4 | Total Error: 0.00002
Iteration 5 | Total Error: 0.00000
Iteration 6 | Total Error: 0.00000
Iteration 7 | Total Error: 0.00000
Iteration 8 | Total Error: 0.00000
Iteration 9 | Total Error: 0.00000

Final Optimized Weight Matrix:
[[ 4.78158911e-02  9.60094505e-02 -3.07367168e-01]
 [ 1.02293807e-01  2.00175409e-01  3.23831574e-04]
 [-9.92071521e-02  1.29241357e+00  8.59942844e-02]]


#### Truth labels are your Goal Posts.
In supervised learning, the network is essentially a "guessing machine." The Truth Labels are the "Right Answers" provided by the dataset.

#### Forward Pass: (Games, Stats) · (Stats, Recipes) = (Games, Recipes)

#### Backward Pass: (Recipes, Games) · (Games, Stats) = (Recipes, Stats)

#### 1. The Core Philosophy

A Neural Network is a Translation Layer. It translates Evidence (Inputs) into Predictions (Outputs) using Knowledge (Weights).
#### 2. The Forward Pass: "The Prediction Flow"

Logic: How much does my current knowledge match this evidence?

    Formula: Predictions = Inputs · Weights.T

    Dimensional Logic: (Samples, Features) · (Features, Hidden/Output)

    The "Tree" Visualization: Each input feature branches out to every output neuron. The dot product is the "flow" of electricity moving from the leaves to the trunk.

#### 3. The Backward Pass: "The Blame Flow"

Logic: Which specific piece of knowledge is responsible for which mistake?

    The Delta (Error): Error = Predictions - Targets

        Shape: (Samples, Outputs) — A map of "Oops" for every guess.

    The Gradient (Blame): Weight_Updates = Error.T · Inputs

        Shape: (Outputs, Samples) · (Samples, Features) = (Outputs, Features)

    The "Aha!" Realization: By transposing the Error, you are looking at the mistake from the perspective of the Expert. By dotting it with the Input, you are asking: "Which input was active when I made this specific mistake?"

#### 4. The "Golden Rule" of Shapes

Whenever you are stuck or seeing a ValueError: shapes not aligned, remember this:

    Forward: The Columns of the first must match the Rows of the second. (Features must meet Features).

    Backward: The Columns of the Error (Samples) must match the Rows of the Input (Samples). (We are averaging the blame across all examples).

#### 5. Why this is Universal

Whether you have 1 layer or 100 layers:

    Forward: Activation_Next = Activation_Current · Weights_Current.T

    Backward: Weight_Gradient = Error_Next.T · Activation_Current



In [7]:
import numpy as np

# --- 1. THE ARCHITECTURE (The Setup) ---
# Weights shape: (3 Experts, 3 Facts)
# Expert 0: Sad | Expert 1: Hurt | Expert 2: Win
weights = np.array([
    [0.1, 0.1, -0.3], # Sad expert's knobs for [Win%, Toes, Fans]
    [0.1, 0.2, 0.0],  # Hurt expert's knobs for [Win%, Toes, Fans]
    [0.0, 1.3, 0.1]   # Win expert's knobs for [Win%, Toes, Fans]
])

# Inputs shape: (4 Games, 3 Facts)
inputs = np.array([
    [8.5, 0.65, 1.2], # Game 1 Evidence
    [9.5, 0.8, 1.3],  # Game 2 Evidence
    [9.9, 0.8, 0.5],  # Game 3 Evidence
    [9.0, 0.9, 1.0]   # Game 4 Evidence
])

# Targets shape: (4 Games, 3 Truths)
# What actually happened in those 4 games
targets = np.array([
    [0.1, 1, 0.1], 
    [0.0, 1, 0.0], 
    [0.0, 0, 0.1], 
    [0.1, 1, 0.2]
])

alpha = 0.01

# --- 2. THE DYNAMICS (The Training) ---
for epoch in range(20):

    # STEP 1: FORWARD PASS (The "Guessing" Phase)
    # Alignment: (4 Games, 3 Facts) dot (3 Facts, 3 Experts)
    # We transpose weights to make the 'Facts' columns line up.
    # Result: (4, 3) -> A guess for every expert for every game.
    preds = inputs.dot(weights.T)

    # STEP 2: COMPARE (The "Regret" Phase)
    # How much did each expert miss the mark in each game?
    # Result: (4, 3) matrix of 'Oops'
    deltas = preds - targets

    # STEP 3: BACKPROP (The "Blame Assignment" Phase)
    # This is the magic: weight_deltas = deltas.T.dot(inputs)
    # We take (3 Experts, 4 Games) dot (4 Games, 3 Facts)
    # This multiplies the 'Oops' by the 'Evidence' that caused it.
    # If the Oops was high AND Evidence was high, the Blame is HUGE.
    weight_deltas = deltas.T.dot(inputs)

    # STEP 4: UPDATE (The "Fixing" Phase)
    # Update all 9 knobs at once based on the average blame across 4 games.
    weights -= (alpha * weight_deltas) / len(inputs)

    if epoch % 5 == 0:
        error = np.mean(deltas ** 2)
        print(f"Epoch {epoch} | System Error: {error:.6f}")

print(f"\nLearned Experts (Weights):\n{weights}")

Epoch 0 | System Error: 0.616221
Epoch 5 | System Error: 0.079402
Epoch 10 | System Error: 0.078558
Epoch 15 | System Error: 0.077723

Learned Experts (Weights):
[[ 0.02906646  0.09418615 -0.29870403]
 [ 0.05952026  0.19858213  0.02608448]
 [-0.10852837  1.28980615  0.0850303 ]]


### StreetLight problem

In [26]:
import numpy as np

streetlights = np.array([ [ 1, 0, 1 ], [ 0, 1, 1 ], [ 0, 0, 1 ], [ 1, 1, 1 ] ])
walk_vs_stop = np.array([ [ 0 ], [ 1 ], [ 0 ], [ 1 ] ])

# Fix 1: Make weights (1, 3) instead of (3,)
weights = np.array([[0.5, 0.48, -0.7]])
alpha = 0.1

# Fix 2: Use slicing [0:1] to keep the 2D shape (1, 3)
input_data = streetlights[0:1] 
goal = walk_vs_stop[0:1]

for i in range(40):
    # (1, 3) dot (3, 1) -> weights.T flips (1, 3) to (3, 1)
    pred = input_data.dot(weights.T) 
    
    delta = pred - goal
    error = delta ** 2
    
    # The "Blame": (1, 1) dot (1, 3) -> Result (1, 3)
    # This matches the weight shape perfectly!
    weight_update = delta.dot(input_data) 

    weights -= (weight_update * alpha)
    

    print(f"Iteration {i} | Error: {error[0][0]:.6f} | Pred: {pred[0][0]:.6f}")

# After training...
all_preds = streetlights.dot(weights.T)
# Round predictions: True if > 0.5, then convert to int (1 or 0)
rounded_preds = (all_preds > 0.5).astype(int)

# Compare with actual targets
accuracy = np.mean(rounded_preds == walk_vs_stop)
print(f"Final Accuracy: {accuracy * 100}%")

Iteration 0 | Error: 0.040000 | Pred: -0.200000
Iteration 1 | Error: 0.025600 | Pred: -0.160000
Iteration 2 | Error: 0.016384 | Pred: -0.128000
Iteration 3 | Error: 0.010486 | Pred: -0.102400
Iteration 4 | Error: 0.006711 | Pred: -0.081920
Iteration 5 | Error: 0.004295 | Pred: -0.065536
Iteration 6 | Error: 0.002749 | Pred: -0.052429
Iteration 7 | Error: 0.001759 | Pred: -0.041943
Iteration 8 | Error: 0.001126 | Pred: -0.033554
Iteration 9 | Error: 0.000721 | Pred: -0.026844
Iteration 10 | Error: 0.000461 | Pred: -0.021475
Iteration 11 | Error: 0.000295 | Pred: -0.017180
Iteration 12 | Error: 0.000189 | Pred: -0.013744
Iteration 13 | Error: 0.000121 | Pred: -0.010995
Iteration 14 | Error: 0.000077 | Pred: -0.008796
Iteration 15 | Error: 0.000050 | Pred: -0.007037
Iteration 16 | Error: 0.000032 | Pred: -0.005629
Iteration 17 | Error: 0.000020 | Pred: -0.004504
Iteration 18 | Error: 0.000013 | Pred: -0.003603
Iteration 19 | Error: 0.000008 | Pred: -0.002882
Iteration 20 | Error: 0.000005

In [27]:
import numpy as np

streetlights = np.array([ [1,0,1], [0,1,1], [0,0,1], [1,1,1], [0,1,1], [1,0,1] ])
walk_vs_stop = np.array([ [0], [1], [0], [1], [1], [0] ])

weights = np.array([[0.5, 0.48, -0.7]])
alpha = 0.1

for i in range(40):
    # Forward Pass: (6, 3) dot (3, 1) -> (6, 1) matrix of predictions
    preds = streetlights.dot(weights.T)
    
    # Calculate Error
    error = (preds - walk_vs_stop) ** 2
    delta = preds - walk_vs_stop
    
    # The "Batch Blame": (1, 6) dot (6, 3) -> (1, 3) update
    # This averages the blame across all 6 games!
    weight_update = delta.T.dot(streetlights)

    weights -= (weight_update * alpha)

# --- CHECK ACCURACY ---
final_preds = streetlights.dot(weights.T)
rounded_preds = (final_preds > 0.5).astype(int)
accuracy = np.mean(rounded_preds == walk_vs_stop)

print(f"Final Weights: {weights}")
print(f"Final Accuracy: {accuracy * 100}%")

Final Weights: [[ 0.01664748  1.0165119  -0.01856317]]
Final Accuracy: 100.0%


### Stochastic Gradient Descent (SGD) :
#### this is what the code in my files looks like. It looks at Row 1, calculates error, and immediately updates the weights. Then it looks at Row 2 and updates again.
* Analogy: A student who checks the answer key after every single question.

### Full Gradient Descent: 
#### It calculates the error of all rows, averages the "blame", and updates the weights once per iteration.
* Analogy: A student who finishes the entire practice test before checking the answer key.

### Batch Gradient Descent: 
#### This is the middle ground (e.g., update after every 2 or 4 rows)

### Weight Pressure:

* Upward pressure(+): When an input is 1 and the goal is 1, the network wants that weight to be higher to reach the goal

* Downward pressure(-): When an input is 1 but the goal is 0, the network realizes this input is "lying" to it. It pushes the weight toward 0 to silence that input.

* Zero pressure(0): If the input is 0, that specific light is off. It doesn't matter what the weight is; It can't contribute to the error, so it feels no pressure.

#### correlation is more than just proportionality—it is a measure of how much information one variable provides about another. In this case, it’s about how much the "state" of a streetlight (on/off) predicts the "state" of your feet (walk/stop).

### Linear vs. Nonlinear
#### A single-layer network is Linear. It can only draw a straight line to separate "Walk" from "Stop." If your data looks like a "sandwich" (e.g., Walk if Light 1 is ON or Light 3 is ON, but STOP if both are ON), a straight line can't cut it.

    Linear: y=wx+b. It’s a straight slope.

    Nonlinear: We use an Activation Function (like ReLU).

    ReLU (Rectified Linear Unit): If the input is negative, make it 0. If positive, keep it.
    f(x)=max(0,x)

    This "bend" in the math allows the network to model curves and complex shapes.

### Learning Indirect Correlation
Sometimes, Input A doesn't correlate with the Output directly, but the combination of A and B does.

    Direct: "Middle light is ON → Walk."

    Indirect: "If Light 1 is ON AND Light 2 is OFF → Walk."
    A Hidden Layer creates "Intermediate Experts" that look for these specific combinations (features) before passing the result to the final layer.

### Edge Case: Conflicting Pressure
This happens when a weight gets pushed "Up" by one example and "Down" by another with equal force.

    In a single layer, the weight just vibrates around zero and never learns.

    In a Deep Network, different hidden neurons can "specialize." One neuron handles the "Up" cases, another handles the "Down" cases, and the output layer decides which one to listen to.

### Overfitting (The "Memorization" Trap)
Overfitting is when your network becomes so good at predicting your specific 6 streetlights that it fails on a new streetlight it hasn't seen before. It starts modeling the noise instead of the pattern.

    Analogy: A student who memorizes the exact numbers in a physics problem instead of learning the formula F=ma.
